version: '3.7'
services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin
      - MINIO_BROWSER_REDIRECT_URL=https://minio.example.com
    volumes:
      - /home/minio:/data
      - /home/container/minio/config:/tmp/.mc
    networks:
      - traefik-public
#    ports:
#      - "9091:9000"
#      - "9090:9090"
    tty: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == your-swarm-nodename
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        # minio-api
        - traefik.http.routers.minio-api.tls=true
        - traefik.http.routers.minio-api.service=minio-api
        - traefik.http.routers.minio-api.rule=Host(`minioapi.example.com`)
        - traefik.http.services.minio-api.loadbalancer.server.port=9000
        # minio-console https
        - traefik.http.routers.minio-console.tls=true
        - traefik.http.routers.minio-console.service=minio-console
        - traefik.http.routers.minio-console.rule=Host(`minio.example.com`)
        - traefik.http.services.minio-console.loadbalancer.server.port=9090
networks:
  traefik-public:
    external: true
